export const responses = {
    'hello': 'Hi there! How can I assist you?',
    'hi': 'Hello! How can I help you today?',
    'hey': 'Hey there! What can I do for you?',
    'how are you': 'I\'m just a chatbot, but thanks for asking!',
    'help': 'What can I help you with?',
    'see you': 'Take care! See you soon.',
    'general knowledge': 'What would you like to know?',
    'physics': 'What specific question do you have about physics?',
    'Whats up?': 'Not much, how can I assist you today?',
    'How are you?': 'I am just a computer program, but I am functioning normally. How can I help you?',
    'who is vineet kumar sinha': 'Vineet Kumar sinha is a great scientist?',
    'greetings': 'Greetings! What can I help you with?',
    'What is your name?': 'I am ChatGPT, a language model trained by OpenAI. How can I assist you today?',
    'How are you?': 'As an AI language model, I do not have feelings in the human sense, but I am always here to help you. What can I do for you today?',

    'What can you do?': 'I can help you with a variety of tasks such as answering questions, providing information, and assisting with basic tasks.',
'How are you doing today?': 'As an AI, I don not have emotions but I am always ready and available to assist you.',


// states and capitals of india
'What is the capital of Andhra Pradesh?': 'The capital of Andhra Pradesh is Amaravati.',
'What is the capital of Arunachal Pradesh?': 'The capital of Arunachal Pradesh is Itanagar.',
'What is the capital of Assam?': 'The capital of Assam is Dispur.',
'What is the capital of Bihar?': 'The capital of Bihar is Patna.',
'What is the capital of Chhattisgarh?': 'The capital of Chhattisgarh is Raipur.',
'What is the capital of Goa?': 'The capital of Goa is Panaji.',
'What is the capital of Gujarat?': 'The capital of Gujarat is Gandhinagar.',
'What is the capital of Haryana?': 'The capital of Haryana is Chandigarh.',
'What is the capital of Himachal Pradesh?': 'The capital of Himachal Pradesh is Shimla.',
'What is the capital of Jharkhand?': 'The capital of Jharkhand is Ranchi.',
'What is the capital of Karnataka?': 'The capital of Karnataka is Bengaluru.',
'What is the capital of Kerala?': 'The capital of Kerala is Thiruvananthapuram.',
'What is the capital of Madhya Pradesh?': 'The capital of Madhya Pradesh is Bhopal.',
'What is the capital of Maharashtra?': 'The capital of Maharashtra is Mumbai.',
'What is the capital of Manipur?': 'The capital of Manipur is Imphal.',
'What is the capital of Meghalaya?': 'The capital of Meghalaya is Shillong.',
'What is the capital of Mizoram?': 'The capital of Mizoram is Aizawl.',
'What is the capital of Nagaland?': 'The capital of Nagaland is Kohima.',
'What is the capital of Odisha?': 'The capital of Odisha is Bhubaneswar.',
'What is the capital of Punjab?': 'The capital of Punjab is Chandigarh.',
'What is the capital of Rajasthan?': 'The capital of Rajasthan is Jaipur.',
'What is the capital of Sikkim?': 'The capital of Sikkim is Gangtok.',
'What is the capital of Tamil Nadu?': 'The capital of Tamil Nadu is Chennai.',
'What is the capital of Telangana?': 'The capital of Telangana is Hyderabad.',
'What is the capital of Tripura?': 'The capital of Tripura is Agartala.',
'What is the capital of Uttar Pradesh?': 'The capital of Uttar Pradesh is Lucknow.',
'What is the capital of Uttarakhand?': 'The capital of Uttarakhand is Dehradun.',
'What is the capital of West Bengal?': 'The capital of West Bengal is Kolkata.',
'What is the capital of Delhi?': 'The capital of Delhi is New Delhi.',
'What is the capital of Jammu and Kashmir?': 'The capital of Jammu and Kashmir is Srinagar (Summer) and Jammu (Winter).',
'What is the capital of Ladakh?': 'The capital of Ladakh is Leh.',
'What is the capital of Ladakh?': 'The capital of Ladakh is Leh.',
'What is the capital of Puducherry?': 'The capital of Puducherry is Pondicherry.',
'What is the capital of Andaman and Nicobar Islands?': 'The capital of Andaman and Nicobar Islands is Port Blair.',
'What is the capital of Lakshadweep?': 'The capital of Lakshadweep is Kavaratti.',
'What is the capital of Dadra and Nagar Haveli and Daman and Diu?': 'The capital of Dadra and Nagar Haveli and Daman and Diu is Daman.',

'What is the capital of Chandigarh?': 'The capital of Chandigarh is Chandigarh.',
'What is the capital of Andaman and Nicobar Islands?': 'The capital of Andaman and Nicobar Islands is Port Blair.',
'What is the capital of Lakshadweep?': 'The capital of Lakshadweep is Kavaratti.',
'What is the capital of Dadra and Nagar Haveli and Daman and Diu?': 'The capital of Dadra and Nagar Haveli and Daman and Diu is Daman.',
'What is the capital of Meghalaya?': 'The capital of Meghalaya is Shillong.',




// class 12 physics
'What is the formula for velocity?': 'The formula for velocity is v = d/t, where v is velocity, d is displacement, and t is time.',
'What is the formula for acceleration?': 'The formula for acceleration is a = (v-u)/t, where a is acceleration, v is final velocity, u is initial velocity, and t is time.',
'What is Newtons first law of motion?': 'Newtons first law of motion states that an object at rest will remain at rest and an object in motion will remain in motion at a constant velocity unless acted upon by an external force.',
'What is Newtons second law of motion?': 'Newtons second law of motion states that the force acting on an object is directly proportional to the mass of the object and its acceleration.',
'What is Newtons third law of motion?': 'Newtons third law of motion states that for every action, there is an equal and opposite reaction.',
'What is work done?': 'Work done is the product of force and displacement in the direction of force, i.e. W = F * d * cosθ, where W is work done, F is force, d is displacement, and θ is the angle between force and displacement.',
'What is power?': 'Power is the rate at which work is done or energy is transferred, i.e. P = W/t or P = F * v, where P is power, W is work done, t is time, F is force, and v is velocity.',
'What is kinetic energy?': 'Kinetic energy is the energy possessed by an object due to its motion, and it is given by the formula K.E. = 1/2 * m * v^2, where m is mass and v is velocity.',
'What is potential energy?': 'Potential energy is the energy possessed by an object due to its position or configuration, and it is given by the formula P.E. = mgh, where m is mass, g is acceleration due to gravity, and h is height.',
'What is the law of conservation of energy?': 'The law of conservation of energy states that energy can neither be created nor destroyed, it can only be transformed from one form to another.',
'What is the principle of superposition?': 'The principle of superposition states that when two or more waves meet at a point, the resultant displacement is equal to the algebraic sum of the individual displacements.',
'What is interference?': 'Interference is the phenomenon of the superposition of two or more waves resulting in a new wave pattern.',
'What is diffraction?': 'Diffraction is the bending of waves around obstacles or through narrow openings.',
'What is the Doppler effect?': 'The Doppler effect is the change in frequency of a wave due to the relative motion between the source of the wave and the observer.',
'What is electromagnetic radiation?': 'Electromagnetic radiation is a form of energy that is propagated through free space or through a material medium in the form of electromagnetic waves.',
'What is electromagnetic spectrum?': 'The electromagnetic spectrum is the range of all possible frequencies of electromagnetic radiation.',
'What is refraction of light?': 'Refraction of light is the bending of light when it passes from one medium to another with a different refractive index.',
'What is total internal reflection?': 'Total internal reflection is the phenomenon of the reflection of all the incident light back into the same medium.',
'What is lens?': 'A lens is a piece of transparent material (such as glass) with at least one curved surface that is used to refract light and form an image.',
'What is focal length?': 'Focal length is the distance between the center of a lens and its focus point, i.e. the point where parallel rays of light converge after passing through the lens.',
'What is the difference between real and virtual image?': 'A real image is formed when the rays of light actually converge at a point after passing through a lens, whereas a virtual image is formed when the rays of light only appear to diverge from a point after passing through a lens.',
'What is diffraction grating?': 'A diffraction grating is a device consisting of a large number of equally spaced parallel slits that diffract light and produce a spectrum of colors.',
'What is polarization of light?': 'Polarization of light is the phenomenon of restricting the vibration of light to a particular plane by using a polarizer.',
'What is photoelectric effect?': 'Photoelectric effect is the phenomenon of the emission of electrons from a metal surface when it is illuminated by light of certain frequencies or higher energies.',
'What is the work function of a metal?': 'The work function of a metal is the minimum amount of energy required to remove an electron from the surface of the metal.',
'What is the threshold frequency?': 'The threshold frequency is the minimum frequency of light required to cause the emission of electrons from a metal surface in the photoelectric effect.',
'What is blackbody radiation?': 'Blackbody radiation is the electromagnetic radiation emitted by a perfect blackbody at a given temperature.',
'What is Planck’s constant?': 'Planck’s constant is a fundamental physical constant that relates the energy of a photon to its frequency, and it has a value of 6.626 x 10^-34 J s.',
'What is the wave-particle duality?': 'The wave-particle duality is the principle that all matter and energy exhibit both wave-like and particle-like properties.',
'What is the uncertainty principle?': 'The uncertainty principle is a fundamental principle of quantum mechanics that states that the more precisely the position of a particle is known, the less precisely its momentum can be known, and vice versa.',
'What is the Schrödinger equation?': 'The Schrödinger equation is the fundamental equation of quantum mechanics that describes the wave-like behavior of particles.',
'What is quantum tunneling?': 'Quantum tunneling is the phenomenon of a particle penetrating a potential barrier that it would not be able to penetrate according to classical physics.',
'What is the Heisenberg uncertainty principle?': 'The Heisenberg uncertainty principle is a more general form of the uncertainty principle that applies to all pairs of observables that do not commute.',
'What is nuclear fission?': 'Nuclear fission is the process of splitting a heavy nucleus into two lighter nuclei of approximately equal mass, releasing a large amount of energy in the process.',
'What is nuclear fusion?': 'Nuclear fusion is the process of combining two light nuclei to form a heavier nucleus, releasing a large amount of energy in the process.',
'What is radioactivity?': 'Radioactivity is the spontaneous emission of radiation from the nucleus of an atom.',
'What is alpha decay?': 'Alpha decay is a type of radioactive decay in which an alpha particle (two protons and two neutrons) is emitted from the nucleus of an atom.',
'What is beta decay?': 'Beta decay is a type of radioactive decay in which a beta particle (an electron or positron) is emitted from the nucleus of an atom.',
'What is gamma decay?': 'Gamma decay is a type of radioactive decay in which a gamma ray (high-energy photon) is emitted from the nucleus of an atom.',

'What is half-life?': 'Half-life is the time required for half of the radioactive atoms in a sample to decay.',
'What is the mass defect?': 'The mass defect is the difference between the mass of an atom and the sum of the masses of its individual protons, neutrons, and electrons.',
'What is binding energy?': 'Binding energy is the energy required to completely separate the protons and neutrons in the nucleus of an atom.',
'What is the mass-energy equivalence?': 'The mass-energy equivalence is the principle that mass and energy are interchangeable, and that the total mass-energy of a system is conserved.',
'What is special relativity?': 'Special relativity is a theory of physics that describes the behavior of objects moving at high speeds relative to each other.',
'What is the Lorentz factor?': 'The Lorentz factor is a mathematical factor that describes how time, length, and mass are affected by high-speed motion according to special relativity.',
'What is time dilation?': 'Time dilation is the phenomenon of time appearing to pass more slowly for a moving object relative to a stationary observer.',
'What is length contraction?': 'Length contraction is the phenomenon of a moving object appearing shorter in the direction of motion relative to a stationary observer.',
'What is the equivalence principle?': 'The equivalence principle is the principle that the force of gravity is equivalent to the force experienced by an observer in an accelerating reference frame.',
'What is the theory of general relativity?': 'The theory of general relativity is a theory of physics that describes the behavior of gravity in terms of the curvature of spacetime.',
'What is the cosmic microwave background radiation?': 'The cosmic microwave background radiation is a faint glow of microwave radiation that permeates the universe, and is thought to be the remnant of the Big Bang.',



// chemistry

'What is chemistry?': 'Chemistry is the scientific study of the properties and behavior of matter.',
'What is matter?': 'Matter is anything that has mass and occupies space.',
'What are atoms?': 'Atoms are the basic units of matter, consisting of a nucleus (protons and neutrons) surrounded by electrons.',
'What is the atomic number?': 'The atomic number is the number of protons in the nucleus of an atom, which determines the element.',
'What is an isotope?': 'An isotope is a variant of an element that has the same number of protons but a different number of neutrons.',
'What is a molecule?': 'A molecule is a group of two or more atoms that are chemically bonded together.',
'What is a compound?': 'A compound is a substance composed of two or more different elements chemically combined in a fixed proportion.',
'What is a chemical reaction?': 'A chemical reaction is a process that results in the transformation of one set of chemical substances to another.',
'What is a chemical equation?': 'A chemical equation is a symbolic representation of a chemical reaction.',
'What is stoichiometry?': 'Stoichiometry is the calculation of the quantities of reactants and products in a chemical reaction.',
'What is a mole?': 'A mole is a unit of measurement used in chemistry to express amounts of a substance.',
'What is Avogadros number?': 'Avogadros number is the number of particles (atoms, molecules, etc.) in one mole of a substance, which is approximately 6.02 × 10^23.',
'What is molarity?': 'Molarity is a measure of the concentration of a solution, defined as the number of moles of solute per liter of solution.',
'What is a solution?': 'A solution is a homogeneous mixture of two or more substances.',
'What is an acid?': 'An acid is a substance that donates hydrogen ions (H+) in a chemical reaction.',
'What is a base?': 'A base is a substance that accepts hydrogen ions (H+) in a chemical reaction.',
'What is pH?': 'pH is a measure of the acidity or basicity of a solution, with values ranging from 0 (most acidic) to 14 (most basic).',

'What is an electrolyte?': 'An electrolyte is a substance that conducts electricity when dissolved in water or melted.',
'What is an ion?': 'An ion is an atom or molecule that has a net electric charge due to the loss or gain of one or more electrons.',
'What is an oxidation-reduction reaction?': 'An oxidation-reduction reaction is a chemical reaction in which electrons are transferred from one atom or molecule to another.',
'What is a redox reaction?': 'A redox reaction is another name for an oxidation-reduction reaction, where there is a transfer of electrons from one species to another.',
'What is a half-reaction?': 'A half-reaction is a part of an oxidation-reduction reaction that shows either the loss of electrons (oxidation) or gain of electrons (reduction).',
'What is a catalyst?': 'A catalyst is a substance that increases the rate of a chemical reaction without itself being consumed in the process.',
'What is an enzyme?': 'An enzyme is a type of catalyst that is produced by living cells and facilitates biochemical reactions in the body.',
'What is activation energy?': 'Activation energy is the minimum amount of energy required for a chemical reaction to occur.',
'What is an exothermic reaction?': 'An exothermic reaction is a chemical reaction that releases heat or energy to the surroundings.',
'What is an endothermic reaction?': 'An endothermic reaction is a chemical reaction that absorbs heat or energy from the surroundings.',
'What is a limiting reagent?': 'A limiting reagent is the reactant in a chemical reaction that is completely consumed, limiting the amount of product that can be formed.',
'What is a yield?': 'A yield is the amount of product formed in a chemical reaction.',
'What is a double displacement reaction?': 'A double displacement reaction is a chemical reaction where two ionic compounds exchange ions to form two new ionic compounds.',
'What is a single displacement reaction?': 'A single displacement reaction is a chemical reaction where one element or ion replaces another element or ion in a compound.',
'What is a combustion reaction?': 'A combustion reaction is a chemical reaction between a fuel (such as a hydrocarbon) and an oxidizing agent (such as oxygen) that produces heat and light.',
'What is a spontaneous reaction?': 'A spontaneous reaction is a chemical reaction that occurs without the input of energy and proceeds naturally in a certain direction.',
'What is an entropy?': 'Entropy is a measure of the disorder or randomness of a system, and is related to the number of possible arrangements of the particles in a system.',
'What is the periodic table?': 'The periodic table is a tabular arrangement of the chemical elements, ordered by their atomic number, electron configurations, and chemical properties.',
'What is an atomic mass?': 'Atomic mass is the mass of an atom of a chemical element, expressed in atomic mass units (amu).',
'What is the mole concept?': 'The mole concept is a fundamental concept in chemistry that relates the mass of a substance to its number of particles.',
'What is a chemical bond?': 'A chemical bond is the force of attraction that holds two or more atoms together in a molecule.',
'What is a covalent bond?': 'A covalent bond is a chemical bond in which two or more atoms share electrons in order to achieve a stable electron configuration.',
'What is an ionic bond?': 'An ionic bond is a chemical bond in which one or more electrons are transferred from one atom to another, resulting in the formation of ions that are attracted to each other.',
'What is a polar covalent bond?': 'A polar covalent bond is a type of covalent bond in which the electrons are shared unequally between the two atoms, resulting in a partial positive and partial negative charge on each atom.',
'What is a nonpolar covalent bond?': 'A nonpolar covalent bond is a type of covalent bond in which the electrons are shared equally between the two atoms, resulting in no net charge on either atom.',
'What is the VSEPR theory?': 'The VSEPR theory (Valence Shell Electron Pair Repulsion theory) is a model used in chemistry to predict the geometry of individual molecules from the number of electron pairs surrounding their central atoms.',
'What is hybridization?': 'Hybridization is a process in which atomic orbitals combine to form new hybrid orbitals that have different shapes and energies than the original orbitals.',
'What is a Lewis structure?': 'A Lewis structure is a diagram that represents the arrangement of valence electrons in a molecule, using dots to represent electrons and lines to represent chemical bonds.',
'What is a resonance structure?': 'A resonance structure is a type of Lewis structure in which the electrons are not localized in a single bond or lone pair, but instead are delocalized over multiple bonds or atoms.',
'What is a reaction mechanism?': 'A reaction mechanism is the step-by-step process by which a chemical reaction occurs, including the individual reactions that take place and the intermediates formed along the way.',
'What is an equilibrium constant?': 'An equilibrium constant is a value that relates the concentrations of reactants and products at equilibrium in a chemical reaction, and can be used to predict the direction of a reaction under different conditions.',
'What is Le Chateliers principle?': "Le Chateliers principle is a principle in chemistry that states that a system at equilibrium will respond to any stress or change in conditions by readjusting its equilibrium position in order to counteract the change.",
'What is a Bronsted-Lowry acid?': 'A Bronsted-Lowry acid is a molecule or ion that donates a proton (H+) to another molecule or ion.',
'What is a Bronsted-Lowry base?': 'A Bronsted-Lowry base is a molecule or ion that accepts a proton (H+) from another molecule or ion.',














// maths

'What is the value of pi?': 'The value of pi is approximately equal to 3.14159.',
'What is the Pythagorean Theorem?': 'The Pythagorean Theorem states that in a right triangle, the square of the length of the hypotenuse is equal to the sum of the squares of the lengths of the other two sides.',
'What is a quadratic equation?': 'A quadratic equation is a polynomial equation of the second degree that has one variable.',
'What is a linear equation?': 'A linear equation is an equation in which the variables have a degree of 1.',
'What is the difference between an equation and an inequality?': 'An equation is a statement that asserts the equality of two expressions, while an inequality is a statement that asserts that one expression is greater or less than another.',
'What is a polynomial?': 'A polynomial is a mathematical expression consisting of variables, coefficients, and exponents that are combined using arithmetic operations such as addition, subtraction, multiplication, and division.',
'What is the difference between a polynomial and a monomial?': 'A monomial is a polynomial that consists of a single term, while a polynomial can have one or more terms.',
'What is a limit?': 'A limit is the value that a function approaches as the input approaches a certain value or point.',
'What is a derivative?': 'A derivative is a mathematical concept that describes the rate at which a function changes over time or as the input changes.',
'What is integration?': 'Integration is a mathematical process that determines the area under a curve or the total amount of something over a given period.',
'What is a logarithm?': 'A logarithm is the inverse function of exponentiation. It tells us what power we need to raise a certain base to get a certain number.',
'What is the difference between a natural logarithm and a common logarithm?': 'A natural logarithm has a base of e, while a common logarithm has a base of 10.',
'What is a matrix?': 'A matrix is a rectangular array of numbers, symbols, or expressions arranged in rows and columns.',
'What is a determinant?': 'A determinant is a scalar value that can be calculated from a square matrix.',
'What is a vector?': 'A vector is a mathematical object that has both magnitude and direction.',
'What is a dot product?': 'A dot product is a mathematical operation that takes two vectors and returns a scalar value.',
'What is a cross product?': 'A cross product is a mathematical operation that takes two vectors and returns a third vector that is perpendicular to both.',
'What is a system of linear equations?': 'A system of linear equations is a set of two or more linear equations that are to be solved simultaneously.',
'What is a function?': 'A function is a relation between a set of inputs and a set of possible outputs with the property that each input is related to exactly one output.',
'What is a domain?': 'The domain of a function is the set of all possible input values or independent variables.',
'What is a range?': 'The range of a function is the set of all possible output values or dependent variables.',
'What is a one-to-one function?': 'A one-to-one function is a function in which every output is paired with a unique input.',

'What is a many-to-one function?': 'A many-to-one function is a function in which multiple inputs can produce the same output.',
'What is a vertical line test?': 'The vertical line test is a graphical method used to determine whether a relation is a function or not.',
'What is a complex number?': 'A complex number is a number that consists of a real part and an imaginary part and is usually written in the form a + bi, where a and b are real numbers and i is the imaginary unit.',
'What is Eulers formula?': "Euler's formula states that e^(ix) = cos(x) + i*sin(x), where e is the mathematical constant approximately equal to 2.71828, i is the imaginary unit, and x is a real number.",
'What is a differential equation?': 'A differential equation is a mathematical equation that relates an unknown function to its derivatives or differentials.',
'What is a homogeneous differential equation?': 'A homogeneous differential equation is a differential equation in which all terms contain only the unknown function and its derivatives.',
'What is a nonhomogeneous differential equation?': 'A nonhomogeneous differential equation is a differential equation in which the terms contain both the unknown function and its derivatives as well as additional terms.',
'What is a partial differential equation?': 'A partial differential equation is a differential equation that involves partial derivatives of a function of several variables.',
'What is a boundary value problem?': 'A boundary value problem is a type of differential equation problem that involves finding a solution to a differential equation with conditions specified at the boundary points of the domain.',
'What is a Laplace transform?': 'A Laplace transform is a mathematical operation that converts a function of time into a function of a complex variable s, which represents frequency.',
'What is a Fourier series?': 'A Fourier series is a mathematical representation of a periodic function as a sum of sine and cosine functions of different frequencies.',
'What is a power series?': 'A power series is a mathematical series that represents a function as an infinite sum of powers of a variable.',
'What is a Taylor series?': 'A Taylor series is a mathematical series that represents a function as an infinite sum of powers of a variable, with each term given by a derivative of the function evaluated at a specific point.',
'What is the binomial theorem?': 'The binomial theorem is a formula that gives the expansion of powers of a binomial, or an expression of the form (a+b)^n, where a and b are real numbers and n is a nonnegative integer.',
'What is the principle of mathematical induction?': 'The principle of mathematical induction is a method of proof used to establish a general statement about a set of numbers or objects by proving it for a specific case and then proving that if it holds for one case, it holds for the next case as well.',
'What is a combinatorial problem?': 'A combinatorial problem is a type of problem that involves counting the number of possible arrangements or combinations of a set of objects.',
'What is the pigeonhole principle?': 'The pigeonhole principle is a mathematical principle that states that if there are more pigeons than pigeonholes, then at least one pigeonhole must contain more than one pigeon.',
'What is a permutation?': 'A permutation is an arrangement of objects in a specific order.',
'What is a combination?': 'A combination is a selection of objects from a set without regard to their order.',





// without the and what



};
